Repository dont-think-about/TripGo, pull requests merged in 2023-10, with the labels that each got.

#4 [FIX] ci 세팅 수정
  .github/workflows/android.yml
  app/src/main/java/com/nbcamp/tripgo/data/service/RetrofitModule.kt
  app/src/main/java/com/nbcamp/tripgo/util/extension/ContextExtension.kt
  app/src/main/java/com/nbcamp/tripgo/view/SplashActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeViewModelFactory.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/mypage/calendar/CalendarFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/mypage/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/mypage/reviewwriting/ReviewWritingFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/review/ReviewFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/review/detail/ReviewDetailFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/weather/WeatherFragment.kt
Labels: build failed

#10 [DESIGN] 축제, 여행 화면구현
  app/build.gradle
  app/src/main/res/layout/activity_attractions.xml
  app/src/main/res/layout/activity_attractions_detail.xml
  app/src/main/res/layout/activity_festival.xml
  app/src/main/res/layout/activity_festival_detail.xml
  app/src/main/res/layout/activity_tour.xml
  app/src/main/res/layout/activity_tour_detail.xml
  app/src/main/res/layout/attraction_recyclerview_item.xml
  app/src/main/res/layout/festival_recyclerview_item.xml
  app/src/main/res/layout/tour_recyclerview_item.xml
  app/src/main/res/values/strings.xml
Labels: merge, design

#11 [DISIGN]:SearchActivity UI 작업
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp/tripgo/view/search/Festival/FestivalFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/SearchActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/adapters/ViewPagerAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/attaction/AttractionsFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/tour/TourFragment.kt
  app/src/main/res/drawable/icon_search_close.png
  app/src/main/res/drawable/icon_search_magnify.png
  app/src/main/res/drawable/search_rounded_edit.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_search_attractions.xml
  app/src/main/res/layout/fragment_search_festival.xml
  app/src/main/res/layout/fragment_search_tour.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design

#12 [DESIGN] 로그인/회원가입 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp/tripgo/view/signup/SignUpActivity.kt
  app/src/main/res/drawable/background_edit_text.xml
  app/src/main/res/drawable/background_edit_text_error.xml
  app/src/main/res/drawable/icon_login_google.png
  app/src/main/res/drawable/icon_login_kakao.png
  app/src/main/res/drawable/icon_main_logo.png
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/dialog_password_find.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design

#13 [DESIGN]: Mypage
  app/src/main/java/com/nbcamp/tripgo/view/mypage/reviewwriting/MyPageDialog.kt
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/fragment_favorite_item.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_page_dialog.xml
  app/src/main/res/layout/fragment_profile_modify.xml
  app/src/main/res/values/strings.xml
Labels: design

#21 [FEAT] 홈화면 버튼이벤트 및 인기 있는 축제 목록
  app/src/main/java/com/nbcamp/tripgo/data/model/festivals/Body.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/festivals/FestivalItem.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/festivals/FestivalResponseModel.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/festivals/Header.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/festivals/Items.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/festivals/Response.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/travelers/Body.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/travelers/Header.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/travelers/Items.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/travelers/Response.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/travelers/TravelersCountResponseModel.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/travelers/TravlerItem.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/mapper/HomeMapper.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/model/FestivalEntity.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/model/TravelerEntity.kt
  app/src/main/java/com/nbcamp/tripgo/data/service/RetrofitModule.kt
  app/src/main/java/com/nbcamp/tripgo/data/service/TourApiService.kt
  app/src/main/java/com/nbcamp/tripgo/util/APIResponse.kt
  app/src/main/java/com/nbcamp/tripgo/util/SingleLiveEvent.kt
  app/src/main/java/com/nbcamp/tripgo/util/TourTheme.kt
  app/src/main/java/com/nbcamp/tripgo/util/URL.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeFestivalUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeViewModelFactory.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/adapter/FestivalViewPagerAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/ThemeClickEvent.kt
  app/src/main/res/drawable/indicator_circle_focus_color.xml
  app/src/main/res/drawable/indicator_circle_focus_out_color.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_main_festival_card.xml
Labels: feature

#24 [FEAT] 홈 화면 날씨에 따른 장소 추천 기능
  app/src/main/java/com/nbcamp/tripgo/data/model/keywords/Body.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/keywords/Header.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/keywords/Items.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/keywords/KeywordItem.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/keywords/KeywordSearchResponseModel.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/keywords/Response.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/weathers/Body.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/weathers/Header.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/weathers/Items.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/weathers/Response.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/weathers/WeatherItem.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/weathers/WeatherResponseModel.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/mapper/HomeMapper.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/mapper/WeatherType.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/model/KeywordSearchEntity.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/model/WeatherEntity.kt
  app/src/main/java/com/nbcamp/tripgo/data/service/RetrofitModule.kt
  app/src/main/java/com/nbcamp/tripgo/data/service/TourApiService.kt
  app/src/main/java/com/nbcamp/tripgo/data/service/WeatherService.kt
  app/src/main/java/com/nbcamp/tripgo/util/URL.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeViewModelFactory.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/uistate/HomeFestivalUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/uistate/HomeWeatherUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/valuetype/TourTheme.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/ThemeClickEvent.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: feature

#26 [FEAT] : MyPage transcation
  app/build.gradle
  app/src/main/java/com/nbcamp/tripgo/data/repository/ExamRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/view/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/mypage/reviewwriting/MyPageDialog.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#27 [BUG] : mypagefragment 오타 수정
  app/src/main/java/com/nbcamp/tripgo/view/mypage/MyPageFragment.kt
Labels: bug

#29 [FEAT] 근처에 있는 관광지 목록 기능
  app/src/main/java/com/nbcamp/tripgo/data/model/nearby/Body.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/nearby/Header.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/nearby/Items.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/nearby/NearbyItem.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/nearby/NearbyPlaceResponseModel.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/nearby/Response.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/mapper/HomeMapper.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/model/NearbyPlaceEntity.kt
  app/src/main/java/com/nbcamp/tripgo/data/service/TourApiService.kt
  app/src/main/java/com/nbcamp/tripgo/view/App.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/adapter/FestivalViewPagerAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/adapter/NearbyPlaceAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/uistate/HomeFestivalUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/uistate/HomeNearbyPlaceUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/uistate/HomeWeatherUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/ThemeClickEvent.kt
  app/src/main/res/layout/item_main_tour_card.xml
  app/src/main/res/values/strings.xml
Labels: feature

#32 [FIX] api 호출 데이터가 없을 때의 처리
  app/src/main/java/com/nbcamp/tripgo/data/repository/HomeRepositoryImpl.kt
Labels: bug

#34 [FEAT] 도별 리스트 출력 기능
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/adapter/ProvincePlaceListAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/uistate/HomeProvincePlaceUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/valuetype/AreaCode.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/valuetype/ProvincePlaceEntity.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/ThemeClickEvent.kt
  app/src/main/res/values/strings.xml
Labels: feature

#37 [FIX] 프래그먼트 재생성 방지 작업
  app/src/main/java/com/nbcamp/tripgo/view/main/FragmentPageType.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainViewModel.kt
Labels: bug

#39 [FEAT] : FirebaseAuth를 활용한 로그인 및 버전 다운그래이드
  app/build.gradle
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/login/LogInActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/mypage/MyPageFragment.kt
  build.gradle
Labels: feature

#41 [FIX] 바텀내비게이션 - 마이페이지 하위 프래그먼트 전환 오류
  app/build.gradle
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
Labels: bug

#42 [FEAT] 캘린더 화면 일정 보여주는 기능 구현
  app/src/main/java/com/nbcamp/tripgo/data/repository/CalendarRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/model/CalendarEntity.kt
  app/src/main/java/com/nbcamp/tripgo/util/FestivalTransformer.kt
  app/src/main/java/com/nbcamp/tripgo/util/calendar/OutDateMonthDecorator.kt
  app/src/main/java/com/nbcamp/tripgo/util/calendar/SelectedDayDecorator.kt
  app/src/main/java/com/nbcamp/tripgo/util/calendar/TodayDecorator.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarViewModelFactory.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/ScheduleListAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/uistate/CalendarScheduleUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeFragment.kt
  app/src/main/res/drawable/calendar_selector.xml
  app/src/main/res/drawable/calendar_today_circle.xml
  app/src/main/res/drawable/transparent_calendar_element.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/item_calendar_schedule_card.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#44 [REFACTOR] 안티 패턴 제거 및 수정
  app/src/main/java/com/nbcamp/tripgo/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeViewModel.kt
Labels: refactor

#46 [FEAT] 캘린더 및 일정 목록 클릭 이벤트
  app/build.gradle
  app/src/main/java/com/nbcamp/tripgo/data/repository/model/CalendarEntity.kt
  app/src/main/java/com/nbcamp/tripgo/util/calendar/SelectedDayDecorator.kt
  app/src/main/java/com/nbcamp/tripgo/util/setFancyDialog.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/ScheduleListAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/uistate/CalendarLogInUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/uistate/RunDialogUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/BackClickEvent.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/ThemeClickEvent.kt
  app/src/main/java/com/nbcamp/tripgo/view/mypage/reviewwriting/ReviewWritingFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/CalendarUserEntity.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/ReviewWritingFragment.kt
  app/src/main/res/drawable/icon_alert_review.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_review_writing.xml
  app/src/main/res/layout/item_calendar_schedule_card.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#48 [FEAT] 리뷰 작성, 수정 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp/tripgo/data/repository/GalleryRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/ReviewWritingRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/model/GalleryPhotoEntity.kt
  app/src/main/java/com/nbcamp/tripgo/util/LoadingDialog.kt
  app/src/main/java/com/nbcamp/tripgo/util/calendar/SelectedDayDecorator.kt
  app/src/main/java/com/nbcamp/tripgo/util/checkPermission.kt
  app/src/main/java/com/nbcamp/tripgo/util/setFancyDialog.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/WritingType.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/uistate/CalendarScheduleUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/PermissionEvent.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/CalendarUserModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/ReviewWritingEvent.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/ReviewWritingFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/ReviewWritingModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/ReviewWritingRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/ReviewWritingViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/ReviewWritingViewModelFactory.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/gallery/GalleryActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/gallery/GalleryPhotoListAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/gallery/GalleryPhotoRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/gallery/GalleryUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/gallery/GalleryViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/gallery/GalleryViewModelFactory.kt
  app/src/main/res/drawable/background_frame_gallery.xml
  app/src/main/res/drawable/icon_check.xml
  app/src/main/res/drawable/icon_gallery.xml
  app/src/main/res/drawable/icon_map.xml
  app/src/main/res/layout/activity_gallery.xml
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_review_writing.xml
  app/src/main/res/layout/item_calendar_schedule_card.xml
  app/src/main/res/layout/item_gallery_photo.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#49 [FEAT]:투어 페이지 가족여행 , 힐링 , 캠핑 , 맛집 조회 기능
  app/src/main/java/com/nbcamp/tripgo/data/model/festivals/FestivalItem.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/keywords/KeywordItem.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/TourActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/adapter/TourAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/adapter/TourSearchAdapter.kt
  app/src/main/res/values/strings.xml
Labels: feature

#52 [FEAT] 관광 상세 페이지 정보 표시
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp/tripgo/data/model/detailcommon/Body.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/detailcommon/DetailCommonItem.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/detailcommon/DetailCommonResponseModel.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/detailcommon/Header.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/detailcommon/Items.kt
  app/src/main/java/com/nbcamp/tripgo/data/model/detailcommon/Response.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/TourDetailRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/mapper/DetailMapper.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/model/DetailCommonEntity.kt
  app/src/main/java/com/nbcamp/tripgo/data/service/TourApiService.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/DetailCommonUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TextClickEvent.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailViewModelFactory.kt
  app/src/main/res/layout/activity_tour_detail.xml
  app/src/main/res/values/strings.xml
Labels: feature

#54 [FEAT] 회원가입 기본 로직 작성 & 파이어스토어 연동
  app/build.gradle
  app/src/main/java/com/nbcamp/tripgo/view/signup/SignUpActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/signup/SignUpViewModel.kt
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: feature

#56 [FEAT] 캘린더 유효성 검사
  app/src/main/java/com/nbcamp/tripgo/data/repository/TourDetailRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/util/calendar/CantSetDayDecorator.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/BackClickEvent.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailViewModelFactory.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/uistate/CalendarSetScheduleUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/uistate/DetailCommonUiState.kt
  app/src/main/res/drawable/calendar_today_circle.xml
  app/src/main/res/drawable/icon_close.xml
  app/src/main/res/layout/dialog_calendar.xml
  app/src/main/res/values/strings.xml
Labels: feature

#60 [FEAT] 일정 추가 기능 구현
  .github/workflows/android.yml
  app/src/main/java/com/nbcamp/tripgo/data/repository/TourDetailRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/mapper/DetailMapper.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/uistate/AddScheduleUiState.kt
  app/src/main/res/values/strings.xml
Labels: feature

#63 [FEAT]:TourActivity 거리순 / 날짜순 클릭이벤트
  app/src/main/java/com/nbcamp/tripgo/view/tour/TourActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/adapter/TourAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/adapter/TourSearchAdapter.kt
  app/src/main/res/layout/activity_tour.xml
  app/src/main/res/values/strings.xml
Labels: feature

#68 [FEAT]: 각종 로그인시 DB에 정보저장되게끔 처리완료
  app/src/main/java/com/nbcamp/tripgo/view/login/LogInActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/signup/SignUpActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/signup/SignUpViewModel.kt
Labels: feature

#69 [FEAT] 관광지 좋아요(찜) 기능 구현
  app/src/main/java/com/nbcamp/tripgo/data/repository/TourDetailRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailViewModel.kt
  app/src/main/res/layout/activity_tour_detail.xml
  app/src/main/res/values/strings.xml
Labels: feature

#71 [FEAT] 검색기능으로 데이터값 받아오기
  app/build.gradle
  app/src/main/java/com/nbcamp/tripgo/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/Festival/FestivalFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/Festival/FestivalViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/Festival/FestivalViewModelFactory.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/SearchActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/SearchAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/SearchKeywordUiState.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/SearchRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/SearchViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/Searchitem.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/adapters/ViewPagerAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/attaction/AttractionsFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/attaction/AttractionsViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/attaction/AttractionsViewModelFactory.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/tour/TourFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/tour/TourViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/tour/TourViewModelFactory.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_search.xml
Labels: feature

#73 [FEAT] 내 일정 추가 시 일정 범위 제한
  app/src/main/java/com/nbcamp/tripgo/data/repository/GalleryRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/util/ConnectWatcher.kt
  app/src/main/java/com/nbcamp/tripgo/util/DetectNetwork.kt
  app/src/main/java/com/nbcamp/tripgo/util/calendar/TodayDecorator.kt
  app/src/main/java/com/nbcamp/tripgo/view/App.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/ScheduleListAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailViewModel.kt
  app/src/main/res/values/strings.xml
Labels: bug, feature

#75 [FEAT]:TourActivity 인기 있는 여행지 거리순 / 날짜순 작업
  app/src/main/java/com/nbcamp/tripgo/view/tour/TourActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/adapter/TourAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/adapter/TourSearchAdapter.kt
  app/src/main/res/layout/tour_recyclerview_item.xml
Labels: feature

#77 [FEAT] 스플래시 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/lottie_5.json
  app/src/main/java/com/nbcamp/tripgo/view/SplashActivity.kt
  app/src/main/res/anim/slide_down_exit.xml
  app/src/main/res/anim/slide_up_enter.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/themes.xml
Labels: feature

#79 [HOTFIX] 테마 수정
  app/src/main/res/values/themes.xml
Labels: bug

#84 [FEAT] TourActivity 거리순 / 날짜순 클릭시 색상 변경
  app/src/main/java/com/nbcamp/tripgo/view/tour/TourActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/adapter/TourAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/adapter/TourSearchAdapter.kt
Labels: feature, design

#82 [FEAT] 회원가입 유효성 검사 + 이메일 인증
  app/src/main/java/com/nbcamp/tripgo/view/signup/SignUpActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/signup/SignUpViewModel.kt
  app/src/main/res/drawable/background_check_box.xml
  app/src/main/res/drawable/background_edit_text_correct.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: feature

#87 [FEAT] 비밀번호 찾기 기능 구현
  app/src/main/java/com/nbcamp/tripgo/view/login/LogInActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/login/PasswordFindFragment.kt
  app/src/main/res/values/style.xml
Labels: feature

#89 [FEAT]: DB 호출
  app/src/main/java/com/nbcamp/tripgo/view/App.kt
  app/src/main/java/com/nbcamp/tripgo/view/login/LogInActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/signup/SignUpViewModel.kt
Labels: feature

#90 [FEAT] 캘린더 프래그먼트에서의 일정 삭제 및 수정 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp/tripgo/data/repository/CalendarRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/ReviewWritingRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/TourDetailRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/model/CalendarEntity.kt
  app/src/main/java/com/nbcamp/tripgo/util/SwipeToEditCallback.kt
  app/src/main/java/com/nbcamp/tripgo/util/calendar/CalendarFragmentTodayDecorator.kt
  app/src/main/java/com/nbcamp/tripgo/util/extension/StringExtension.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/ScheduleListAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/ScheduleModifyFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/modify/TourModifyDetailActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailViewModel.kt
  app/src/main/res/drawable/calendar_today_circle.xml
  app/src/main/res/drawable/icon_schedule_modify.xml
  app/src/main/res/layout/dialog_calendar_modify.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/item_calendar_schedule_card.xml
  app/src/main/res/values/strings.xml
Labels: feature

#94 [FIX] 시연 영상 촬영 전 확인 되는 버그 수정
  app/src/main/java/com/nbcamp/tripgo/view/calendar/CalendarFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/modify/ScheduleModifyFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/modify/TourModifyDetailActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/home/HomeFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailViewModel.kt
  app/src/main/res/layout/activity_tour_detail.xml
  app/src/main/res/layout/item_calendar_schedule_card.xml
  app/src/main/res/values/strings.xml
Labels: bug

#95 [FEAT} 검색페이지 지도 구현
  app/build.gradle
  app/src/main/java/com/nbcamp/tripgo/view/search/Festival/FestivalViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/SearchActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/SearchAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/Searchitem.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/attaction/AttractionsViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/search/tour/TourViewModel.kt
  app/src/main/res/layout/activity_search.xml
Labels: feature

#100 [FIX] 일정 선택 유효성 수정 및 리뷰 작성 모델 구조 변경
  app/src/main/java/com/nbcamp/tripgo/data/repository/ReviewWritingRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/model/UserModel.kt
  app/src/main/java/com/nbcamp/tripgo/util/MapConverter.kt
  app/src/main/java/com/nbcamp/tripgo/view/main/MainViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/ReviewWritingFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/ReviewWritingModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/ReviewWritingRepository.kt
  app/src/main/java/com/nbcamp/tripgo/view/reviewwriting/ReviewWritingViewModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailViewModel.kt
Labels: bug, feature

#103 [FEAT]: 리뷰 등급제 세팅
  app/src/main/java/com/nbcamp/tripgo/data/repository/ReviewWritingRepositoryImpl.kt
  app/src/main/java/com/nbcamp/tripgo/data/repository/model/UserModel.kt
  app/src/main/java/com/nbcamp/tripgo/view/login/LogInActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/signup/SignUpViewModel.kt
Labels: feature

#105 [FIX] kakao map 연결부분까지
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp/tripgo/view/search/SearchActivity.kt
  app/src/main/res/layout/activity_search.xml
  build.gradle
Labels: refactor

#108 [FEAT] Tour , Atrractions Activity : 사용자 권한 얻기
  app/src/main/java/com/nbcamp/tripgo/view/attraction/AttractionsActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/TourActivity.kt
  app/src/main/res/values/strings.xml
Labels: attraction-page, tour-page

#110 [FEAT] 관광 상세페이지 tmap -> kakao map 교체
  .github/workflows/android.yml
  app/build.gradle
  app/libs/tmap-sdk-1.2.aar
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp/tripgo/util/KaKaoMapFrameLayout.kt
  app/src/main/java/com/nbcamp/tripgo/util/TMapFrameLayout.kt
  app/src/main/java/com/nbcamp/tripgo/view/calendar/modify/TourModifyDetailActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailActivity.kt
  app/src/main/java/com/nbcamp/tripgo/view/tour/detail/TourDetailViewModel.kt
  app/src/main/res/layout/activity_tour_detail.xml
  app/src/main/res/values/strings.xml
Labels: tour-detail-page

#112 [FEAT] : Mypage -> review page부분 DB 불러와 item에 넣고 adapter를 이용한 recycle…
  app/src/main/java/com/nbcamp/tripgo/view/review/ReviewAdapter.kt
  app/src/main/java/com/nbcamp/tripgo/view/review/ReviewFragment.kt
  app/src/main/java/com/nbcamp/tripgo/view/review/Reviewdata.kt
Labels: review-page
